VALIDATION_RATIO = 0.2
TEST_RATIO = 0.2
DATASET_IMAGE_DIMENSIONS = (32, 32, 3)
BATCH_SIZE = 50
EPOCHS = 30

COLUMN_COUNT_FOR_EXAMPLE_IMAGES_GRAPH = 5
FIGURE_SIZE_FOR_EXAMPLE_IMAGES_GRAPH = (5, 300)

FIGURE_SIZE_FOR_DATASET_DISTRIBUTION_GRAPH = (12, 4)

FIGURE_SIZE_FOR_EXAMPLE_PROCESSED_IMAGE = (8, 8)

WIDTH_SHIFT_RATIO_FOR_AUGMENTATION = 0.1
HEIGHT_SHIFT_RATIO_FOR_AUGMENTATION = 0.1
ZOOM_RATIO_FOR_AUGMENTATION = 0.2
SHEAR_RATIO_FOR_AUGMENTATION = 0.1
ROTATION_FOR_AUGMENTATION = 10

ROWS_FOR_EXAMPLE_FOR_A_BATCH_OF_AUGMENTED_IMAGES = 1
COLUMNS_FOR_EXAMPLE_FOR_A_BATCH_OF_AUGMENTED_IMAGES = 15
FIGURE_SIZE_FOR_AUGMENTED_IMAGE_EXAMPLES = (20, 5)
FONT_SIZE_FOR_AUGMENTED_IMAGE_EXAMPLES = 16

NUMBER_OF_FILTERS_FOR_MODEL = 60
SIZE_OF_FILTER_FOR_FIRST_2D_LAYERS_FOR_MODEL = (5, 5)
SIZE_OF_FILTER_FOR_LAST_2D_LAYERS_FOR_MODEL = (3, 3)
SIZE_OF_POOL_FOR_MODEL = (2, 2)
NUMBER_OF_NODES_FOR_MODEL = 500


def main():
    return 0


if __name__ == "__main__":
    main()
